### ISSUE TITLE
Notify when new torrents have been added

### ISSUE THREAD

**Issue by agneevX** [zeroone2numeral2/qbittorrent-bot#35]
Pretty much the title :)

**Comment by zeroone2numeral2** [comment]
Do you mean, from other qbittorrent clients?

**Comment by agneevX** [comment]
Yes, that is correct

**Comment by zeroone2numeral2** [comment]
Okay, I will try to add that when I have time. Unfortunately, it will be quite hard to know whether a torrent has been added from an external client or from a torrent file sent to the bot. That's because the qbittorrent api doesn't tell me the hash of a torrent added as .torrent file

I would implement the feature this way:
- when the bot starts, it saves the hashes list of the currently added torrents
- every n minutes a job looks for new torrents (hash not in the list we saved on startup)
- when a torrent is added through the bot via magnet link, we append the hash we can extract from the magnet to the currently know hashes list

the problem here as I previously said, is that with torrent files I am not aware of the torrent hash we are adding. So when the periodic job runs, it will think that the torrent added via file through the bot is a new torrent because its hash is not in the list. I'll see what I can do about that

**Comment by landjie** [comment]
Please add copy upload GD function

**Comment by zeroone2numeral2** [comment]
I'm dumb, this was easier than I expected: I can simply send the notification message directly when a torrent is added, without setting up a new job

The config file has now a new option, `new_torrents_notification`: you can set a chat ID here where to send a notification when a new torrent (magnet/file/url) is added. The notification will not be sent if the target chat is the user who just added the torrent
