### ISSUE TITLE
Get completed download notification

### ISSUE THREAD

**Issue by jaum20** [zeroone2numeral2/qbittorrent-bot#66]
`completed_torrents = 0 # id of a chat to notify when a torrent is completed. 0 to disable`

How can I get the ID of the chat? I am no using the bot in any group. I get an error message: `exception: an error occurred while running the job notify_completed(): Chat not found`. It is in some way a notification of completed download lol But I would like to know which torrent is completed

**Comment by zeroone2numeral2** [comment]
You can set your ID, this way the bot will send you a message every time a torrent is completed

To get your ID you can message to [@myid_bot](https://t.me/myid_bot)

**Comment by jaum20** [comment]
Still no working. My config: 

`completed_torrents = "511573266" # id of a chat to notify when a torrent is completed. 0 to disable
`
I also tried without the quotation marks. Same error exception: `an error occurred while running the job notify_completed(): Chat not found`

**Comment by zeroone2numeral2** [comment]
Two things that come to mind:
- you are editing `config.example.toml` instead of `config.toml`
- you haven't sent a message to the bot in a long time (unlikely)

These are the only two things I could think of.  It would be helpful to know the full error traceback.

One thing you could try, btw, is setting a channel as the target chat for notifications:
1. create the channel
2. add the bot as an administrator, with the permission to post messages
3. send a message in the channel, anything
4. forward that message to the bot I previously messaged
5. copy the channel's id in `config.toml` (as an integer, no quotes)

**Comment by jaum20** [comment]
> * you are editing `config.example.toml` instead of `config.toml`

nope, I am sure that I am editing `config.toml`

> * you haven't sent a message to the bot in a long time (unlikely)

also no.

I will try the channel approach. Thanks

**Comment by jaum20** [comment]
Using a channel id worked for me. Thanks
